# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nakzzi
tagline:          ''
description:      'Made by <a href="https://github.com/cholnh/" target="_blank">@Nakzzi</a>.'
url:              

author:
  name:           'Choi Nak Hyung'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cholnh/
