# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nakzzi Note
tagline:          'Software Development'
description:      'Made by [@Nakzzi](mailto:cholnh486@gmail.com).'
url:              

author:
  name:           'Choi Nak Hyung'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cholnh/
